import { Building } from "types/building";

export const transformBuildingToFormValues = (data: Building) => {
	return {
		name: data?.name ?? "",
		buildingType: data?.buildingType,
		description: data?.description ?? "",
		activate: data?.activate,
		occupancyStatus: data?.occupancyStatus,
		property_type: data?.buildingFacts?.buildingOverview?.property_type,
		year_built: data?.buildingFacts?.buildingOverview?.year_built,
		building_class: data?.buildingFacts?.buildingOverview?.building_class,
		owner: data?.buildingFacts?.buildingOverview?.owner,
		units: data?.buildingFacts?.sizeAndDimensions?.units,
		stories: data?.buildingFacts?.sizeAndDimensions?.stories,
		building_Sq_Ft: data?.buildingFacts?.sizeAndDimensions?.building_Sq_Ft,
		lot_Sq_Ft: data?.buildingFacts?.sizeAndDimensions?.lot_Sq_Ft,
		building_depth: data?.buildingFacts?.sizeAndDimensions?.building_depth,
		community_district: data?.buildingFacts?.districts?.community_district,
		police_precinct: data?.buildingFacts?.districts?.police_precinct,
		school_district: data?.buildingFacts?.districts?.school_district,
		city_council: data?.buildingFacts?.districts?.city_council,
		fire_department: data?.buildingFacts?.districts?.fire_department,
		dogs: data?.petsPolicy?.dogs,
		cats: data?.petsPolicy?.cats,
		smallPets: data?.petsPolicy?.smallPets,
		noPets: data?.petsPolicy?.noPets,
		petsOnApproval: data?.petsPolicy?.petsOnApproval,
		address: data?.address?.address,
		advertisingAddress: data?.address?.advertisingAddress,
		state: data?.address?.state,
		borough: data?.address?.borough,
		city: data?.address?.city,
		country: data?.address?.country,
		neighborhood: data?.address?.neighborhood,
		advertisingLatitude: data?.address?.advertisingLatitude,
		advertisingLongitude: data?.address?.advertisingLongitude,
		crossStreet: data?.address?.crossStreet,
		latitude: data?.address?.latitude,
		longitude: data?.address?.longitude,
		meetingPlace: data?.address?.meetingPlace,
		note: data?.address?.note,
		zip: data?.address?.zip,
		amenities: data?.amenities,
		utilities: data?.utilities,
		contactsData: data?.contactsData,
		contacts: data?.contacts
	};
};
