export const RoomTypes = {
	singleRoom: "singleRoom",
	doubleRoom: "doubleRoom",
	twinRoom: "twinRoom",
	suite: "suite",
	deluxeRoom: "deluxeRoom",
	executiveSuite: "executiveSuite",
	familyRoom: "familyRoom",
	connectingRooms: "connectingRooms",
	bedroom: "bedroom",
	masterBedroom: "masterBedroom",
	guestRoom: "guestRoom",
	childrensRoom: "childrensRoom",
	nursery: "nursery",
	livingRoom: "livingRoom",
	diningRoom: "diningRoom",
	kitchen: "kitchen",
	bathroom: "bathroom",
	homeOffice: "homeOffice",
	studyRoom: "studyRoom",
	gameRoom: "gameRoom",
	mediaRoom: "mediaRoom",
	utilityRoom: "utilityRoom",
	studioApartment: "studioApartment",
	oneBedroomApartment: "oneBedroomApartment",
	twoBedroomApartment: "twoBedroomApartment",
	penthouse: "penthouse",
	conferenceRoom: "conferenceRoom",
	boardroom: "boardroom",
	receptionArea: "receptionArea",
	cubiclesOpenOffice: "cubiclesOpenOffice",
	executiveOffice: "executiveOffice",
	breakRoom: "breakRoom",
	trainingRoom: "trainingRoom",
	classroom: "classroom",
	lectureHall: "lectureHall",
	laboratory: "laboratory",
	library: "library",
	patientRoom: "patientRoom",
	operatingRoom: "operatingRoom",
	examinationRoom: "examinationRoom",
	waitingRoom: "waitingRoom",
	salesFloor: "salesFloor",
	fittingRoom: "fittingRoom",
	stockRoom: "stockRoom",
	gym: "gym",
	spaRoom: "spaRoom",
	homeTheater: "homeTheater",
	lobby: "lobby",
	waitingArea: "waitingArea",
	restroom: "restroom",
	serverRoom: "serverRoom",
	panicRoom: "panicRoom",
	safeRoom: "safeRoom",
	wineCellar: "wineCellar",
	Sunroom: "Sunroom",
	Mudroom: "Mudroom"
} as const;

export const FeeTypes = {
	fee: "fee",
	noFee: "noFee",
	shiftingFee: "shiftingFee"
} as const;

export const RoomStatuses = {
	new: "new",
	vacant: "vacant",
	rented: "rented"
} as const;
